name: fl_formz
description: Flutter text editing controller that can automatically validate form.
version: 0.0.2
repository: "https://github.com/amir1430/fl_form"

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  formz: ^0.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter: null
